### ISSUE TITLE
How did you download your solutions?

### ISSUE THREAD

**Issue by lucifer1004** [MdAbedin/binarysearch#1]
Did you keep a local backup or did you manage to get your data from the site owner? If it was the latter, I really hope you can share how you did this.

**Comment by MdAbedin** [comment]
I uploaded my solutions to github manually back when the site existed.

I messaged one of the founders, Lawrence Wu, on twitter on October 18 to ask what happened to the site but he didn't reply.

**Comment by lucifer1004** [comment]
Thank you for your reply!
